### ISSUE TITLE
Skillchains SMN pet skills

### ISSUE THREAD

**Issue by bardicrune** [Sippius/Ashita-v4-addons#1] opened 2023-01-15 04:42 UTC
Was testing the skillchains port to v4 (ty btw).  Found an issue with SMN pet skills not showing as an opener for my WS.  I attempted 
> /sc pet

but received the message
> Unable to set pet on THF

I modified the line:
> Show = T{burst=jobs, pet=T{'BST','SMN','THF'}, props=jobs, spell=T{'SCH','BLU'}, step=jobs, timer=jobs, weapon=jobs},

to include THF under pet and now could toggle the message:
> pet info will no(w,t) be displayed.

but still could not see the SMN's carbuncle's Poison Nails skill as a valid opening skill.

Poison Nails > Wasp Sting = Distortion

If this functionality could be added it would be nice(r).

**Comment by Sippius** [comment] 2023-01-16 06:09
I ran a very quick test on retail and it looks to be working as expected. Are you on a private server? If you are, it is possible that they have modified some of the games internal values which is causing your issues.

**Comment by bardicrune** [comment] 2023-01-16 15:54
Yes, HorizonXI.

**Comment by Sippius** [comment] 2023-02-03 01:01
Reading back through your original post, it looks like you are expecting Poison Nails to show up before any weaponskills have been executed. The addon doesn't work that way. After executing an initial weaponskill or petskill, the addon will display skills that will create a skillchain. In your example of Poison Nails > Wasp Sting, the display will not show up until after Poinson Nails goes off. When the display comes up, you would see Wasp Sting in the list.

If you are still looking for a solution, you can try out the new chains addon. It is a more heavily modified port of skillchains. It is still designed and tested on retail only so any HorizonXI specific changes are not accounted for.

**Comment by Chibloom** [comment] 2023-02-03 04:29
I am not the op, but even as the summoner main casting pet skills on the same private server(horizon), the skillchains display never popped up, even if I could have followed up with my own dagger. It does show that I can followup a weaponskill with a blood pact, but even after using it the display does not acknowledge it. The pet skill is going off and landed, but no display came up at all.

I have not tried chains addon for this yet.

**Comment by Sippius** [comment] 2023-02-03 05:33
On retail I get the display after first step with poison nails. I expect your issue is due to something Horizon changed. I can't debug it.

**Comment by Chibloom** [comment] 2023-02-03 06:12
Is there any way to help provide data why this is occurring?

**Comment by Sippius** [comment] 2023-02-04 06:37
I'll can create some debug prints to make it easier to see what's going on. It won't be until next week though.

**Comment by Sippius** [comment] 2023-02-06 04:24
The latest version (0.5) allows for some debug prints of actions. Prints can be enabled using "/chains debug".
For Poison Nails you should get Type = 13, Id = 513 and Action Message = 317

**Comment by bardicrune** [comment] 2023-02-07 03:31
I was previously working with the older skillchains addon, not the newer chains addon.  I have downloaded the newer addon (chains v0.5) and will test the next time I am in a party with a SMN.

**Comment by Chibloom** [comment] 2023-02-09 03:45
![image](https://user-images.githubusercontent.com/86545774/217712698-57ed9ce7-41e3-41c6-9181-b49b7afb3425.png)
looks like mismatch in type and action messages
i understand that type 13 is called for summoner bloodpacts, however the skill id is differing here so it cannot identify

skills[13] = { -- BST/SMN Pet Skills
    [513] = {en='Poison Nails',skillchain={'Transfixion'}},

The type 6 ID 513 is understood as the ability/command. As there is no type 6, the addon cannot identify what is ID 513 then(idk programing well). Type 6 seems to refer to the pet commands section / the orders
The type 13 ID 907 is understood as the actual hit. ID 907 is nonexistent in type 13 so it cannot identify the skill.

**Comment by Chibloom** [comment] 2023-02-09 03:47
![image](https://user-images.githubusercontent.com/86545774/217713100-8263bdfc-2d59-4f6c-b744-b8fe17a30baf.png)
for comparison

**Comment by Chibloom** [comment] 2023-02-09 03:57
![image](https://user-images.githubusercontent.com/86545774/217714226-35edc1e5-9230-46b5-91d2-61664e8bbc61.png)
![image](https://user-images.githubusercontent.com/86545774/217714249-eddae54f-4913-48e7-adb7-391295a1343d.png)
ifrit for comparison

**Comment by Chibloom** [comment] 2023-02-09 03:58
> ![image](https://user-images.githubusercontent.com/86545774/217712698-57ed9ce7-41e3-41c6-9181-b49b7afb3425.png) looks like mismatch in type and action messages

modifying skills lua for poison nail to be id 907 has made the popup appear however 
![image](https://user-images.githubusercontent.com/86545774/217714414-1fafd973-35aa-4b19-893f-82d34abbe4a4.png)
![image](https://user-images.githubusercontent.com/86545774/217714476-7f7bc6ac-5d6f-46fd-a674-07b0f19131a9.png)
i am unsure where it is attempting to grab on type 6 as that is not a listed section

**Comment by Chibloom** [comment] 2023-02-09 04:15
I do not code so I am unsure if this is relevant
https://gitlab.com/airskyboat/airskyboat/-/blob/staging/scripts/globals/ability.lua
AirSkyBoat, the repo that Horizion is based on to my understanding.
Meanwhile mobskills have their ids for pet weaponskills https://gitlab.com/airskyboat/airskyboat/-/blob/staging/sql/mob_skills.sql
INSERT INTO `mob_skills` VALUES (907,606,'poison_nails',0,10.0,497,3000,4,4,0,0,1,0,0); -- Transfixion (1)

This private server does not have beastmaster weaponskills I believe so I cannot help you there, nor have it leveled.

meanwhile this is for weaponskills https://gitlab.com/airskyboat/airskyboat/-/blob/staging/scripts/globals/weaponskillids.lua , seems identical to what you already have so no need to worry about it.

**Comment by Chibloom** [comment] 2023-02-09 04:24
I have also looked into WingsXI gitlab and the same case is here
https://gitlab.com/ffxiwings/wings/-/blob/master/sql-wings/mob_skills.sql
INSERT INTO `mob_skills` VALUES(907, 606, 'poison_nails', 0, 10.0, 497, 3000, 4, 0, 0, 0, 1, 0, 0);

**Comment by Sippius** [comment] 2023-02-09 04:31
Action Message 317 vs 185 doesn't make a difference. The problem is the Id.  

The skills.lua file needs to be updated to match what the private server uses or an alternative method that is consistent across the two platforms needs to be used.

I'm not sure of an alternat method off hand, but I may poke around the airskyboat files a little.

The quickest way at this point would be to update skills.lua

**Comment by Sippius** [comment] 2023-02-09 06:49
FYI...

Type 6 is for Job Ability. In this case, it is the players action to trigger the pet skill. 
Type 13 is for Avatar TP finish. 
On retail, the pet packet ID is the same value as the player packet ID to trigger the skill. At least that is what I'm seeing. I don't know much about the packet content.

**Comment by bardicrune** [comment] 2023-02-18 04:28
### **Below Post References v0.5**

After finally getting a party with a summoner on HorizonXI, I have verified the findings made by Chibloom.

I have modified the skills.lua to reflect the changed ID's from retail.  I based the IDs on the values in mob_skills.sql.  The IDs match for both AirSkyBoat and Wings with the exception of 'Tickling Tendrils' (missing from Wings).

I have added my modified skills.lua to:
[https://github.com/bardicrune/chainsskills4horizonxi](https://github.com/bardicrune/chainsskills4horizonxi)

These changes have not been validated as I need another party with a SMN to do so.

**Comment by bardicrune** [comment] 2023-02-18 05:14
Didn't notice the update to v0.6.  I will modify and test with that going forward.

**Comment by bardicrune** [comment] 2023-02-18 17:49
I was modifying the v0.6 skills.lua and noticed a couple of problems with the ASB values of some skills.
Claw - The ASB value you have recorded is 876.  It should be 867.
Whirl Claws - The ASB value you have recorded is 258.  It should be 259.
??? Needles - The ASB value you have recorded is 322.  I believe it should be 3867.  322 equates to 1000 Needles.

For any HorizonXI players, I have posted the modified skills.lua for v0.6 at:
[https://github.com/bardicrune/chainsskills4horizonxi](https://github.com/bardicrune/chainsskills4horizonxi)

**Comment by bardicrune** [comment] 2023-02-28 15:04
Found a format error in skills.lua
Current:
[226] = {en='Requiescat',skillchain={'Gravitation','Scission'},aeonic='Darkness',weapon=-'Sequence'},
Should be:
[226] = {en='Requiescat',skillchain={'Gravitation','Scission'},aeonic='Darkness',weapon='Sequence'},

Erroneous '-' after 'weapon='

**Comment by Sippius** [comment] 2023-03-01 02:23
fixed typo. Thanks

**Closed as completed** 2023-03-20 23:03 UTC
